apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-sentinel-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: redis-sentinel
