apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: {{ .Values.namespace }}
  labels:
    app: redis-sentinel
spec:
  serviceName: "redis-sentinel"
  replicas: {{ .Values.replicaCount.sentinel }}
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      initContainers:
        - name: init-sentinel-config
          image: busybox:1.36.1
          command: ["/bin/sh","-c"]
          args:
            - |
              set -euo pipefail
              COUNT=0
              until nc -z -w1 redis-0.redis 6379 || [ $COUNT -gt 30 ]; do
                echo "Waiting for redis-0 at redis-0.redis:6379 ..."
                COUNT=$((COUNT+1))
                sleep 2
              done
              PW="$(cat /auth/redis-password)"
              mkdir -p /config
              cp /config-src/sentinel.conf /config/sentinel.conf
              echo "sentinel auth-pass mymaster ${PW}" >> /config/sentinel.conf
          volumeMounts:
            - name: sentinel-config-gen
              mountPath: /config
            - name: redis-config
              mountPath: /config-src
            - name: redis-auth
              mountPath: /auth
              readOnly: true
      containers:
        - name: sentinel
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/sh","-c"]
          args: ["exec redis-sentinel /config/sentinel.conf"]
          ports:
            - containerPort: 26379
              name: sentinel
          resources:
            {{- toYaml .Values.resources.sentinel | nindent 12 }}
          volumeMounts:
            - name: sentinel-config-gen
              mountPath: /config
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
        - name: redis-auth
          secret:
            secretName: redis-auth
        - name: sentinel-config-gen
          emptyDir: {}
