namespace: redis-cluster

image:
  repository: redis
  tag: "8.2.1"

replicaCount:
  redis: 3
  sentinel: 3

resources:
  redis:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  sentinel:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

persistence:
  enabled: true
  size: 5Gi
  #storageClassName: gp3

password: "MySecurePass123!"
